// validate form fields
function validateFormField(fieldId, errorMessage, maxLength, defaultLabel) {
    var fieldEl = $('#' + fieldId);
    var fieldValue = fieldEl.val();
    var labelEl = fieldEl.siblings('label');

    if (!fieldValue) {
        fieldEl.css('border', '1px solid red');
        labelEl.css('color', 'red').text(errorMessage);
        return false;
    } else if (maxLength && fieldValue.length > maxLength) {
        fieldEl.css('border', '1px solid red');
        labelEl.css('color', 'red').text(errorMessage);
        return false;
    } else {
        fieldEl.css('border', '1px solid lightgrey');
        labelEl.css('color', 'black').text(defaultLabel);
        return true;
    }
}

let locations = [];

$(document).ready(function(){

    $('form').on('submit', function(e){
        e.stopPropagation();
        e.preventDefault();
        e.stopImmediatePropagation();

        let isValidForm = false;

        let isSearchPage = window.location.pathname.includes('search');
        let isContactPage = window.location.pathname.includes('contact');

        if(isContactPage) {
            isValidFirstName = validateFormField('first-name', 'First Name is required', 255, 'First Name*');
            isValidLastName = validateFormField('lastname', 'Last Name is required', 255, 'Last Name*');
            isValidEmail = validateFormField('email', 'Email is required', 255, 'Email*');

            isValidForm = isValidFirstName && isValidLastName && isValidEmail;
        }

        if(isSearchPage) {
            // TODO: validate form fields based on URL type attr
        }

        // confirm the form is valid for submittion
        if (!isValidForm) {
            console.log('form is in valid', isValidForm)
            return;
        }

        var form = 'page=' + window.location.href + "&" + $('form').serialize() + "&locations=" + locations;
        console.log(form)

        $.ajax({
            type: 'POST',
            url: 'inc/brain.php',
            data: form,
            dataType: 'text',
            success: function(result){

                $('.fade-out').fadeOut();

                $('.status').html(result);

            }
        });

    });

    const myOptions = [

        {label: "Philadelphia (All)", value: "Philadelphia (All)"},
        {label: "Pittsburgh (All)", value: "Pittsburgh (All)"},
        {label: "Aaronsburg", value: "Aaronsburg"},
        {label: "Abbottstown", value: "Abbottstown"},
        {label: "Adamsburg", value: "Adamsburg"},
        {label: "Adamstown", value: "Adamstown"},
        {label: "Addison", value: "Addison"},
        {label: "Akron", value: "Akron"},
        {label: "Albion", value: "Albion"},
        {label: "Alburtis", value: "Alburtis"},
        {label: "Alexandria", value: "Alexandria"},
        {label: "Aliquippa", value: "Aliquippa"},
        {label: "Allenport", value: "Allenport"},
        {label: "Allentown", value: "Allentown"},
        {label: "Allentown ", value: "Allentown "},
        {label: "Altoona", value: "Altoona"},
        {label: "Ambler", value: "Ambler"},
        {label: "Ambridge", value: "Ambridge"},
        {label: "Amity", value: "Amity"},
        {label: "Annville", value: "Annville"},
        {label: "Apollo", value: "Apollo"},
        {label: "Archbald", value: "Archbald"},
        {label: "Ardmore", value: "Ardmore"},
        {label: "Arendtsville", value: "Arendtsville"},
        {label: "Aristes", value: "Aristes"},
        {label: "Arona", value: "Arona"},
        {label: "Ashland", value: "Ashland"},
        {label: "Ashville", value: "Ashville"},
        {label: "Atglen", value: "Atglen"},
        {label: "Auburn", value: "Auburn"},
        {label: "Audubon", value: "Audubon"},
        {label: "Austin", value: "Austin"},
        {label: "Avis", value: "Avis"},
        {label: "Avondale", value: "Avondale"},
        {label: "Avonmore", value: "Avonmore"},
        {label: "Baden", value: "Baden"},
        {label: "Bally", value: "Bally"},
        {label: "Bangor", value: "Bangor"},
        {label: "Bath", value: "Bath"},
        {label: "Beallsville", value: "Beallsville"},
        {label: "Bear Creek", value: "Bear Creek"},
        {label: "Beaver", value: "Beaver"},
        {label: "Beaver Falls", value: "Beaver Falls"},
        {label: "Beaver Meadows", value: "Beaver Meadows"},
        {label: "Beaver Springs", value: "Beaver Springs"},
        {label: "Beaverdale", value: "Beaverdale"},
        {label: "Beavertown", value: "Beavertown"},
        {label: "Bechtelsville", value: "Bechtelsville"},
        {label: "Beech Creek", value: "Beech Creek"},
        {label: "Beechview", value: "Beechview"},
        {label: "Bella Vista", value: "Bella Vista"},
        {label: "Belle Vernon", value: "Belle Vernon"},
        {label: "Bellefonte", value: "Bellefonte"},
        {label: "Belleville", value: "Belleville"},
        {label: "Bellwood", value: "Bellwood"},
        {label: "Bendersville", value: "Bendersville"},
        {label: "Bentleyville", value: "Bentleyville"},
        {label: "Benton", value: "Benton"},
        {label: "Berlin", value: "Berlin"},
        {label: "Bernville", value: "Bernville"},
        {label: "Berrysburg", value: "Berrysburg"},
        {label: "Berwick", value: "Berwick"},
        {label: "Bessemer", value: "Bessemer"},
        {label: "Bethel Park", value: "Bethel Park"},
        {label: "Bethlehem", value: "Bethlehem"},
        {label: "Big Run", value: "Big Run"},
        {label: "Biglerville", value: "Biglerville"},
        {label: "Birdsboro", value: "Birdsboro"},
        {label: "Black Lick", value: "Black Lick"},
        {label: "Blain", value: "Blain"},
        {label: "Blairsville", value: "Blairsville"},
        {label: "Blanchard", value: "Blanchard"},
        {label: "Bloomfield", value: "Bloomfield"},
        {label: "Blooming Glen", value: "Blooming Glen"},
        {label: "Bloomsburg", value: "Bloomsburg"},
        {label: "Blossburg", value: "Blossburg"},
        {label: "Blue Bell", value: "Blue Bell"},
        {label: "Boalsburg", value: "Boalsburg"},
        {label: "Boiling Springs", value: "Boiling Springs"},
        {label: "Bolivar", value: "Bolivar"},
        {label: "Boswell", value: "Boswell"},
        {label: "Bowmanstown", value: "Bowmanstown"},
        {label: "Boyertown", value: "Boyertown"},
        {label: "Brackenridge", value: "Brackenridge"},
        {label: "Braddock", value: "Braddock"},
        {label: "Bradford", value: "Bradford"},
        {label: "Bradfordwoods", value: "Bradfordwoods"},
        {label: "Branchdale", value: "Branchdale"},
        {label: "Bridgeport", value: "Bridgeport"},
        {label: "Brighton Heights", value: "Brighton Heights"},
        {label: "Brisbin", value: "Brisbin"},
        {label: "Bristol", value: "Bristol"},
        {label: "Broad Top", value: "Broad Top"},
        {label: "Brockway", value: "Brockway"},
        {label: "Brodheadsville", value: "Brodheadsville"},
        {label: "Brookhaven", value: "Brookhaven"},
        {label: "Brookline", value: "Brookline"},
        {label: "Brookville", value: "Brookville"},
        {label: "Broomall", value: "Broomall"},
        {label: "Brownstown", value: "Brownstown"},
        {label: "Brownsville", value: "Brownsville"},
        {label: "Bruin", value: "Bruin"},
        {label: "Bryn Athyn", value: "Bryn Athyn"},
        {label: "Bryn Mawr", value: "Bryn Mawr"},
        {label: "Burgettstown", value: "Burgettstown"},
        {label: "Burnham", value: "Burnham"},
        {label: "Burnside", value: "Burnside"},
        {label: "Butler", value: "Butler"},
        {label: "California", value: "California"},
        {label: "Callensburg", value: "Callensburg"},
        {label: "Callery", value: "Callery"},
        {label: "Calumet", value: "Calumet"},
        {label: "Cambridge Springs", value: "Cambridge Springs"},
        {label: "Camp Hill", value: "Camp Hill"},
        {label: "Campbelltown", value: "Campbelltown"},
        {label: "Canonsburg", value: "Canonsburg"},
        {label: "Canton", value: "Canton"},
        {label: "Carbondale", value: "Carbondale"},
        {label: "Carlisle", value: "Carlisle"},
        {label: "Carmichaels", value: "Carmichaels"},
        {label: "Carnegie", value: "Carnegie"},
        {label: "Carrolltown", value: "Carrolltown"},
        {label: "Cashtown", value: "Cashtown"},
        {label: "Catasauqua", value: "Catasauqua"},
        {label: "Catawissa", value: "Catawissa"},
        {label: "Cecil", value: "Cecil"},
        {label: "Center City", value: "Center City"},
        {label: "Centerport", value: "Centerport"},
        {label: "Centerville", value: "Centerville"},
        {label: "Central City", value: "Central City"},
        {label: "Centre Hall", value: "Centre Hall"},
        {label: "Chalfont", value: "Chalfont"},
        {label: "Chambersburg", value: "Chambersburg"},
        {label: "Charleroi", value: "Charleroi"},
        {label: "Cherry Tree", value: "Cherry Tree"},
        {label: "Chester", value: "Chester"},
        {label: "Chester Heights", value: "Chester Heights"},
        {label: "Chestnut Hill", value: "Chestnut Hill"},
        {label: "Chicora", value: "Chicora"},
        {label: "Chinatown", value: "Chinatown"},
        {label: "Christiana", value: "Christiana"},
        {label: "Clairton", value: "Clairton"},
        {label: "Clarence", value: "Clarence"},
        {label: "Clarendon", value: "Clarendon"},
        {label: "Clarion", value: "Clarion"},
        {label: "Clark", value: "Clark"},
        {label: "Clarks Summit", value: "Clarks Summit"},
        {label: "Clarksville", value: "Clarksville"},
        {label: "Claysburg", value: "Claysburg"},
        {label: "Claysville", value: "Claysville"},
        {label: "Clearfield", value: "Clearfield"},
        {label: "Clifton Heights", value: "Clifton Heights"},
        {label: "Clintonville", value: "Clintonville"},
        {label: "Clymer", value: "Clymer"},
        {label: "Coaldale", value: "Coaldale"},
        {label: "Coalport", value: "Coalport"},
        {label: "Coatesville", value: "Coatesville"},
        {label: "Cochranton", value: "Cochranton"},
        {label: "Cokeburg", value: "Cokeburg"},
        {label: "Collegeville", value: "Collegeville"},
        {label: "Columbia", value: "Columbia"},
        {label: "Colver", value: "Colver"},
        {label: "Commodore", value: "Commodore"},
        {label: "Confluence", value: "Confluence"},
        {label: "Conneaut Lake", value: "Conneaut Lake"},
        {label: "Conneautville", value: "Conneautville"},
        {label: "Connellsville", value: "Connellsville"},
        {label: "Connoquenessing", value: "Connoquenessing"},
        {label: "Conshohocken", value: "Conshohocken"},
        {label: "Conway", value: "Conway"},
        {label: "Conyngham", value: "Conyngham"},
        {label: "Coopersburg", value: "Coopersburg"},
        {label: "Cooperstown", value: "Cooperstown"},
        {label: "Coplay", value: "Coplay"},
        {label: "Coraopolis", value: "Coraopolis"},
        {label: "Cornwall", value: "Cornwall"},
        {label: "Corry", value: "Corry"},
        {label: "Corsica", value: "Corsica"},
        {label: "Coudersport", value: "Coudersport"},
        {label: "Crabtree", value: "Crabtree"},
        {label: "Cranesville", value: "Cranesville"},
        {label: "Creekside", value: "Creekside"},
        {label: "Cresson", value: "Cresson"},
        {label: "Cressona", value: "Cressona"},
        {label: "Croydon", value: "Croydon"},
        {label: "Curtisville", value: "Curtisville"},
        {label: "Curwensville", value: "Curwensville"},
        {label: "Daisytown", value: "Daisytown"},
        {label: "Dallas", value: "Dallas"},
        {label: "Dallastown", value: "Dallastown"},
        {label: "Dalton", value: "Dalton"},
        {label: "Danville", value: "Danville"},
        {label: "Darby", value: "Darby"},
        {label: "Darlington", value: "Darlington"},
        {label: "Dauphin", value: "Dauphin"},
        {label: "Davidsville", value: "Davidsville"},
        {label: "Dawson", value: "Dawson"},
        {label: "Dayton", value: "Dayton"},
        {label: "Delano", value: "Delano"},
        {label: "Delaware Water Gap", value: "Delaware Water Gap"},
        {label: "Delmont", value: "Delmont"},
        {label: "Delta", value: "Delta"},
        {label: "Denver", value: "Denver"},
        {label: "Derry", value: "Derry"},
        {label: "Dickson City", value: "Dickson City"},
        {label: "Dillsburg", value: "Dillsburg"},
        {label: "Donora", value: "Donora"},
        {label: "Dover", value: "Dover"},
        {label: "Downtown", value: "Downtown"},
        {label: "Doylestown", value: "Doylestown"},
        {label: "Dravosburg", value: "Dravosburg"},
        {label: "Drexel Hill", value: "Drexel Hill"},
        {label: "Du Bois", value: "Du Bois"},
        {label: "Dublin", value: "Dublin"},
        {label: "Dunbar", value: "Dunbar"},
        {label: "Duncannon", value: "Duncannon"},
        {label: "Duncansville", value: "Duncansville"},
        {label: "Dunlevy", value: "Dunlevy"},
        {label: "Duquesne", value: "Duquesne"},
        {label: "Duryea", value: "Duryea"},
        {label: "Dushore", value: "Dushore"},
        {label: "Eagleville", value: "Eagleville"},
        {label: "East Berlin", value: "East Berlin"},
        {label: "East Brady", value: "East Brady"},
        {label: "East Butler", value: "East Butler"},
        {label: "East Greenville", value: "East Greenville"},
        {label: "East Liberty", value: "East Liberty"},
        {label: "East Mc Keesport", value: "East Mc Keesport"},
        {label: "East Petersburg", value: "East Petersburg"},
        {label: "East Pittsburgh", value: "East Pittsburgh"},
        {label: "East Prospect", value: "East Prospect"},
        {label: "East Stroudsburg", value: "East Stroudsburg"},
        {label: "East Vandergrift", value: "East Vandergrift"},
        {label: "Easton", value: "Easton"},
        {label: "Eau Claire", value: "Eau Claire"},
        {label: "Ebensburg", value: "Ebensburg"},
        {label: "Edinboro", value: "Edinboro"},
        {label: "Elco", value: "Elco"},
        {label: "Elderton", value: "Elderton"},
        {label: "Eldred", value: "Eldred"},
        {label: "Elgin", value: "Elgin"},
        {label: "Elizabeth", value: "Elizabeth"},
        {label: "Elizabethtown", value: "Elizabethtown"},
        {label: "Elizabethville", value: "Elizabethville"},
        {label: "Elkland", value: "Elkland"},
        {label: "Ellsworth", value: "Ellsworth"},
        {label: "Ellwood City", value: "Ellwood City"},
        {label: "Elysburg", value: "Elysburg"},
        {label: "Emigsville", value: "Emigsville"},
        {label: "Emlenton", value: "Emlenton"},
        {label: "Emmaus", value: "Emmaus"},
        {label: "Emporium", value: "Emporium"},
        {label: "Enola", value: "Enola"},
        {label: "Enon Valley", value: "Enon Valley"},
        {label: "Ephrata", value: "Ephrata"},
        {label: "Erie", value: "Erie"},
        {label: "Ernest", value: "Ernest"},
        {label: "Evans City", value: "Evans City"},
        {label: "Everett", value: "Everett"},
        {label: "Everson", value: "Everson"},
        {label: "Export", value: "Export"},
        {label: "Exton", value: "Exton"},
        {label: "Factoryville", value: "Factoryville"},
        {label: "Fairchance", value: "Fairchance"},
        {label: "Fairfield", value: "Fairfield"},
        {label: "Fairless Hills", value: "Fairless Hills"},
        {label: "Fairmount", value: "Fairmount"},
        {label: "Fairview", value: "Fairview"},
        {label: "Falls Creek", value: "Falls Creek"},
        {label: "Farrell", value: "Farrell"},
        {label: "Fawn Grove", value: "Fawn Grove"},
        {label: "Fayette City", value: "Fayette City"},
        {label: "Fayetteville", value: "Fayetteville"},
        {label: "Feasterville Trevose", value: "Feasterville Trevose"},
        {label: "Felton", value: "Felton"},
        {label: "Ferndale", value: "Ferndale"},
        {label: "Finleyville", value: "Finleyville"},
        {label: "Fishtown", value: "Fishtown"},
        {label: "Fleetwood", value: "Fleetwood"},
        {label: "Flourtown", value: "Flourtown"},
        {label: "Folcroft", value: "Folcroft"},
        {label: "Folsom", value: "Folsom"},
        {label: "Ford City", value: "Ford City"},
        {label: "Ford Cliff", value: "Ford Cliff"},
        {label: "Forest City", value: "Forest City"},
        {label: "Forest Grove", value: "Forest Grove"},
        {label: "Forestville", value: "Forestville"},
        {label: "Fort Washington", value: "Fort Washington"},
        {label: "Foxburg", value: "Foxburg"},
        {label: "Frackville", value: "Frackville"},
        {label: "Franklin", value: "Franklin"},
        {label: "Franklintown", value: "Franklintown"},
        {label: "Fredericksburg", value: "Fredericksburg"},
        {label: "Fredericktown", value: "Fredericktown"},
        {label: "Fredonia", value: "Fredonia"},
        {label: "Freeburg", value: "Freeburg"},
        {label: "Freedom", value: "Freedom"},
        {label: "Freeland", value: "Freeland"},
        {label: "Freeport", value: "Freeport"},
        {label: "Friedens", value: "Friedens"},
        {label: "Friedensburg", value: "Friedensburg"},
        {label: "Galeton", value: "Galeton"},
        {label: "Gallitzin", value: "Gallitzin"},
        {label: "Gap", value: "Gap"},
        {label: "Garrett", value: "Garrett"},
        {label: "Gastonville", value: "Gastonville"},
        {label: "Germantown", value: "Germantown"},
        {label: "Gettysburg", value: "Gettysburg"},
        {label: "Gilberton", value: "Gilberton"},
        {label: "Gilbertsville", value: "Gilbertsville"},
        {label: "Girard", value: "Girard"},
        {label: "Glassport", value: "Glassport"},
        {label: "Glen Campbell", value: "Glen Campbell"},
        {label: "Glen Lyon", value: "Glen Lyon"},
        {label: "Glen Rock", value: "Glen Rock"},
        {label: "Glenolden", value: "Glenolden"},
        {label: "Glenside", value: "Glenside"},
        {label: "Gordon", value: "Gordon"},
        {label: "Grampian", value: "Grampian"},
        {label: "Grapeville", value: "Grapeville"},
        {label: "Gratz", value: "Gratz"},
        {label: "Great Bend", value: "Great Bend"},
        {label: "Green Lane", value: "Green Lane"},
        {label: "Greensburg", value: "Greensburg"},
        {label: "Greenville", value: "Greenville"},
        {label: "Grindstone", value: "Grindstone"},
        {label: "Grove City", value: "Grove City"},
        {label: "Halifax", value: "Halifax"},
        {label: "Hallstead", value: "Hallstead"},
        {label: "Hamburg", value: "Hamburg"},
        {label: "Hanover", value: "Hanover"},
        {label: "Harleysville", value: "Harleysville"},
        {label: "Harmonsburg", value: "Harmonsburg"},
        {label: "Harmony", value: "Harmony"},
        {label: "Harrisburg", value: "Harrisburg"},
        {label: "Harrisville", value: "Harrisville"},
        {label: "Hartleton", value: "Hartleton"},
        {label: "Hartstown", value: "Hartstown"},
        {label: "Harveys Lake", value: "Harveys Lake"},
        {label: "Hastings", value: "Hastings"},
        {label: "Hatboro", value: "Hatboro"},
        {label: "Hatfield", value: "Hatfield"},
        {label: "Hawley", value: "Hawley"},
        {label: "Hawthorn", value: "Hawthorn"},
        {label: "Hazleton", value: "Hazleton"},
        {label: "Heilwood", value: "Heilwood"},
        {label: "Hellertown", value: "Hellertown"},
        {label: "Herminie", value: "Herminie"},
        {label: "Hermitage", value: "Hermitage"},
        {label: "Herndon", value: "Herndon"},
        {label: "Hershey", value: "Hershey"},
        {label: "Highspire", value: "Highspire"},
        {label: "Hiller", value: "Hiller"},
        {label: "Hollidaysburg", value: "Hollidaysburg"},
        {label: "Homer City", value: "Homer City"},
        {label: "Homestead", value: "Homestead"},
        {label: "Honesdale", value: "Honesdale"},
        {label: "Honey Brook", value: "Honey Brook"},
        {label: "Hooversville", value: "Hooversville"},
        {label: "Hop Bottom", value: "Hop Bottom"},
        {label: "Hopewell", value: "Hopewell"},
        {label: "Hopwood", value: "Hopwood"},
        {label: "Horsham", value: "Horsham"},
        {label: "Houston", value: "Houston"},
        {label: "Houtzdale", value: "Houtzdale"},
        {label: "Howard", value: "Howard"},
        {label: "Hughesville", value: "Hughesville"},
        {label: "Hummels Wharf", value: "Hummels Wharf"},
        {label: "Hummelstown", value: "Hummelstown"},
        {label: "Hunker", value: "Hunker"},
        {label: "Huntingdon", value: "Huntingdon"},
        {label: "Hyde", value: "Hyde"},
        {label: "Hyde Park", value: "Hyde Park"},
        {label: "Hydetown", value: "Hydetown"},
        {label: "Hyndman", value: "Hyndman"},
        {label: "Imperial", value: "Imperial"},
        {label: "Jackson", value: "Jackson"},
        {label: "Jackson Center", value: "Jackson Center"},
        {label: "Jamestown", value: "Jamestown"},
        {label: "Jeannette", value: "Jeannette"},
        {label: "Jefferson", value: "Jefferson"},
        {label: "Jenkintown", value: "Jenkintown"},
        {label: "Jennerstown", value: "Jennerstown"},
        {label: "Jermyn", value: "Jermyn"},
        {label: "Jerome", value: "Jerome"},
        {label: "Jersey Shore", value: "Jersey Shore"},
        {label: "Jessup", value: "Jessup"},
        {label: "Jim Thorpe", value: "Jim Thorpe"},
        {label: "Johnsonburg", value: "Johnsonburg"},
        {label: "Johnstown", value: "Johnstown"},
        {label: "Jonestown", value: "Jonestown"},
        {label: "Kane", value: "Kane"},
        {label: "Kensington", value: "Kensington"},
        {label: "King Of Prussia", value: "King Of Prussia"},
        {label: "Kingston", value: "Kingston"},
        {label: "Kittanning", value: "Kittanning"},
        {label: "Knox", value: "Knox"},
        {label: "Knoxville", value: "Knoxville"},
        {label: "Koppel", value: "Koppel"},
        {label: "Kreamer", value: "Kreamer"},
        {label: "Kulpmont", value: "Kulpmont"},
        {label: "Kulpsville", value: "Kulpsville"},
        {label: "Kutztown", value: "Kutztown"},
        {label: "Laceyville", value: "Laceyville"},
        {label: "Lake City", value: "Lake City"},
        {label: "Lancaster", value: "Lancaster"},
        {label: "Lanesboro", value: "Lanesboro"},
        {label: "Langhorne", value: "Langhorne"},
        {label: "Lansdale", value: "Lansdale"},
        {label: "Lansdowne", value: "Lansdowne"},
        {label: "Lansford", value: "Lansford"},
        {label: "Laporte", value: "Laporte"},
        {label: "Latrobe", value: "Latrobe"},
        {label: "Lavelle", value: "Lavelle"},
        {label: "Lawrenceville", value: "Lawrenceville"},
        {label: "Lawton", value: "Lawton"},
        {label: "Le Raysville", value: "Le Raysville"},
        {label: "Lebanon", value: "Lebanon"},
        {label: "Leechburg", value: "Leechburg"},
        {label: "Leesport", value: "Leesport"},
        {label: "Leetsdale", value: "Leetsdale"},
        {label: "Lehighton", value: "Lehighton"},
        {label: "Lemont", value: "Lemont"},
        {label: "Lemoyne", value: "Lemoyne"},
        {label: "Levittown", value: "Levittown"},
        {label: "Lewis Run", value: "Lewis Run"},
        {label: "Lewisberry", value: "Lewisberry"},
        {label: "Lewisburg", value: "Lewisburg"},
        {label: "Lewistown", value: "Lewistown"},
        {label: "Liberty", value: "Liberty"},
        {label: "Light Street", value: "Light Street"},
        {label: "Ligonier", value: "Ligonier"},
        {label: "Lilly", value: "Lilly"},
        {label: "Linesville", value: "Linesville"},
        {label: "Lionville", value: "Lionville"},
        {label: "Lititz", value: "Lititz"},
        {label: "Little Meadows", value: "Little Meadows"},
        {label: "Littlestown", value: "Littlestown"},
        {label: "Liverpool", value: "Liverpool"},
        {label: "Lock Haven", value: "Lock Haven"},
        {label: "Loganton", value: "Loganton"},
        {label: "Loganville", value: "Loganville"},
        {label: "Loretto", value: "Loretto"},
        {label: "Lucernemines", value: "Lucernemines"},
        {label: "Luzerne", value: "Luzerne"},
        {label: "Lykens", value: "Lykens"},
        {label: "Lyon Station", value: "Lyon Station"},
        {label: "Macungie", value: "Macungie"},
        {label: "Madison", value: "Madison"},
        {label: "Mahaffey", value: "Mahaffey"},
        {label: "Mahanoy City", value: "Mahanoy City"},
        {label: "Malvern", value: "Malvern"},
        {label: "Manayunk", value: "Manayunk"},
        {label: "Manchester", value: "Manchester"},
        {label: "Manheim", value: "Manheim"},
        {label: "Manns Choice", value: "Manns Choice"},
        {label: "Manor", value: "Manor"},
        {label: "Mansfield", value: "Mansfield"},
        {label: "Mapleton Depot", value: "Mapleton Depot"},
        {label: "Marcus Hook", value: "Marcus Hook"},
        {label: "Marianna", value: "Marianna"},
        {label: "Marietta", value: "Marietta"},
        {label: "Marion Center", value: "Marion Center"},
        {label: "Marion Heights", value: "Marion Heights"},
        {label: "Markleysburg", value: "Markleysburg"},
        {label: "Mars", value: "Mars"},
        {label: "Martin", value: "Martin"},
        {label: "Martinsburg", value: "Martinsburg"},
        {label: "Marysville", value: "Marysville"},
        {label: "Masontown", value: "Masontown"},
        {label: "Matamoras", value: "Matamoras"},
        {label: "Maytown", value: "Maytown"},
        {label: "Mc Alisterville", value: "Mc Alisterville"},
        {label: "Mc Clure", value: "Mc Clure"},
        {label: "Mc Connellsburg", value: "Mc Connellsburg"},
        {label: "Mc Donald", value: "Mc Donald"},
        {label: "Mc Ewensville", value: "Mc Ewensville"},
        {label: "Mc Kean", value: "Mc Kean"},
        {label: "Mc Kees Rocks", value: "Mc Kees Rocks"},
        {label: "Mc Keesport", value: "Mc Keesport"},
        {label: "Mc Sherrystown", value: "Mc Sherrystown"},
        {label: "Mc Veytown", value: "Mc Veytown"},
        {label: "Meadville", value: "Meadville"},
        {label: "Mechanicsburg", value: "Mechanicsburg"},
        {label: "Mechanicsville", value: "Mechanicsville"},
        {label: "Media", value: "Media"},
        {label: "Mercer", value: "Mercer"},
        {label: "Mercersburg", value: "Mercersburg"},
        {label: "Meshoppen", value: "Meshoppen"},
        {label: "Mexico", value: "Mexico"},
        {label: "Meyersdale", value: "Meyersdale"},
        {label: "Middleburg", value: "Middleburg"},
        {label: "Middleport", value: "Middleport"},
        {label: "Middletown", value: "Middletown"},
        {label: "Midland", value: "Midland"},
        {label: "Midtown Village", value: "Midtown Village"},
        {label: "Midway", value: "Midway"},
        {label: "Mifflin", value: "Mifflin"},
        {label: "Mifflinburg", value: "Mifflinburg"},
        {label: "Mifflintown", value: "Mifflintown"},
        {label: "Mifflinville", value: "Mifflinville"},
        {label: "Milesburg", value: "Milesburg"},
        {label: "Milford", value: "Milford"},
        {label: "Mill Creek", value: "Mill Creek"},
        {label: "Mill Hall", value: "Mill Hall"},
        {label: "Mill Village", value: "Mill Village"},
        {label: "Millersburg", value: "Millersburg"},
        {label: "Millerstown", value: "Millerstown"},
        {label: "Millersville", value: "Millersville"},
        {label: "Millheim", value: "Millheim"},
        {label: "Millville", value: "Millville"},
        {label: "Milroy", value: "Milroy"},
        {label: "Milton", value: "Milton"},
        {label: "Minersville", value: "Minersville"},
        {label: "Modena", value: "Modena"},
        {label: "Mohnton", value: "Mohnton"},
        {label: "Monaca", value: "Monaca"},
        {label: "Monessen", value: "Monessen"},
        {label: "Monongahela", value: "Monongahela"},
        {label: "Monroeville", value: "Monroeville"},
        {label: "Mont Alto", value: "Mont Alto"},
        {label: "Montgomery", value: "Montgomery"},
        {label: "Montgomeryville", value: "Montgomeryville"},
        {label: "Montoursville", value: "Montoursville"},
        {label: "Montrose", value: "Montrose"},
        {label: "Moosic", value: "Moosic"},
        {label: "Morrisville", value: "Morrisville"},
        {label: "Morton", value: "Morton"},
        {label: "Moscow", value: "Moscow"},
        {label: "Mount Carmel", value: "Mount Carmel"},
        {label: "Mount Gretna", value: "Mount Gretna"},
        {label: "Mount Holly Springs", value: "Mount Holly Springs"},
        {label: "Mount Jewett", value: "Mount Jewett"},
        {label: "Mount Joy", value: "Mount Joy"},
        {label: "Mount Pleasant", value: "Mount Pleasant"},
        {label: "Mount Pleasant Mills", value: "Mount Pleasant Mills"},
        {label: "Mount Pocono", value: "Mount Pocono"},
        {label: "Mount Union", value: "Mount Union"},
        {label: "Mount Washington", value: "Mount Washington"},
        {label: "Mount Wolf", value: "Mount Wolf"},
        {label: "Mountainhome", value: "Mountainhome"},
        {label: "Mountville", value: "Mountville"},
        {label: "Muncy", value: "Muncy"},
        {label: "Myerstown", value: "Myerstown"},
        {label: "Nanticoke", value: "Nanticoke"},
        {label: "Nanty Glo", value: "Nanty Glo"},
        {label: "Narberth", value: "Narberth"},
        {label: "Nazareth", value: "Nazareth"},
        {label: "Nemacolin", value: "Nemacolin"},
        {label: "Nescopeck", value: "Nescopeck"},
        {label: "Nesquehoning", value: "Nesquehoning"},
        {label: "New Albany", value: "New Albany"},
        {label: "New Alexandria", value: "New Alexandria"},
        {label: "New Berlin", value: "New Berlin"},
        {label: "New Bethlehem", value: "New Bethlehem"},
        {label: "New Brighton", value: "New Brighton"},
        {label: "New Castle", value: "New Castle"},
        {label: "New Columbia", value: "New Columbia"},
        {label: "New Cumberland", value: "New Cumberland"},
        {label: "New Eagle", value: "New Eagle"},
        {label: "New Florence", value: "New Florence"},
        {label: "New Freedom", value: "New Freedom"},
        {label: "New Galilee", value: "New Galilee"},
        {label: "New Holland", value: "New Holland"},
        {label: "New Hope", value: "New Hope"},
        {label: "New Kensington", value: "New Kensington"},
        {label: "New Kingstown", value: "New Kingstown"},
        {label: "New Milford", value: "New Milford"},
        {label: "New Oxford", value: "New Oxford"},
        {label: "New Paris", value: "New Paris"},
        {label: "New Philadelphia", value: "New Philadelphia"},
        {label: "New Ringgold", value: "New Ringgold"},
        {label: "New Salem", value: "New Salem"},
        {label: "New Stanton", value: "New Stanton"},
        {label: "New Wilmington", value: "New Wilmington"},
        {label: "Newburg", value: "Newburg"},
        {label: "Newell", value: "Newell"},
        {label: "Newmanstown", value: "Newmanstown"},
        {label: "Newport", value: "Newport"},
        {label: "Newry", value: "Newry"},
        {label: "Newton Hamilton", value: "Newton Hamilton"},
        {label: "Newtown", value: "Newtown"},
        {label: "Newville", value: "Newville"},
        {label: "Nicholson", value: "Nicholson"},
        {label: "Norristown", value: "Norristown"},
        {label: "North Apollo", value: "North Apollo"},
        {label: "North East", value: "North East"},
        {label: "North Oakland", value: "North Oakland"},
        {label: "North Philadelphia", value: "North Philadelphia"},
        {label: "North Shore", value: "North Shore"},
        {label: "North Versailles", value: "North Versailles"},
        {label: "North Wales", value: "North Wales"},
        {label: "Northampton", value: "Northampton"},
        {label: "Northeast Philadelphia", value: "Northeast Philadelphia"},
        {label: "Northern Cambria", value: "Northern Cambria"},
        {label: "Northern Liberties", value: "Northern Liberties"},
        {label: "Northumberland", value: "Northumberland"},
        {label: "Norwood", value: "Norwood"},
        {label: "Numidia", value: "Numidia"},
        {label: "Nuremberg", value: "Nuremberg"},
        {label: "Oakdale", value: "Oakdale"},
        {label: "Oakmont", value: "Oakmont"},
        {label: "Oil City", value: "Oil City"},
        {label: "Old City", value: "Old City"},
        {label: "Old Forge", value: "Old Forge"},
        {label: "Oliver", value: "Oliver"},
        {label: "Olyphant", value: "Olyphant"},
        {label: "Oneida", value: "Oneida"},
        {label: "Orangeville", value: "Orangeville"},
        {label: "Orbisonia", value: "Orbisonia"},
        {label: "Oreland", value: "Oreland"},
        {label: "Orrstown", value: "Orrstown"},
        {label: "Orwigsburg", value: "Orwigsburg"},
        {label: "Osceola Mills", value: "Osceola Mills"},
        {label: "Oxford", value: "Oxford"},
        {label: "Palmerton", value: "Palmerton"},
        {label: "Palmyra", value: "Palmyra"},
        {label: "Paoli", value: "Paoli"},
        {label: "Paradise", value: "Paradise"},
        {label: "Parker", value: "Parker"},
        {label: "Parkesburg", value: "Parkesburg"},
        {label: "Parryville", value: "Parryville"},
        {label: "Patton", value: "Patton"},
        {label: "Paxtonville", value: "Paxtonville"},
        {label: "Pen Argyl", value: "Pen Argyl"},
        {label: "Penn", value: "Penn"},
        {label: "Penns Creek", value: "Penns Creek"},
        {label: "Penn's Landing", value: "Penn's Landing"},
        {label: "Pennsburg", value: "Pennsburg"},
        {label: "Pennsport", value: "Pennsport"},
        {label: "Perkasie", value: "Perkasie"},
        {label: "Perryopolis", value: "Perryopolis"},
        {label: "Petersburg", value: "Petersburg"},
        {label: "Petrolia", value: "Petrolia"},
        {label: "Philipsburg", value: "Philipsburg"},
        {label: "Phoenixville", value: "Phoenixville"},
        {label: "Picture Rocks", value: "Picture Rocks"},
        {label: "Pillow", value: "Pillow"},
        {label: "Pine Grove", value: "Pine Grove"},
        {label: "Pine Grove Mills", value: "Pine Grove Mills"},
        {label: "Pitcairn", value: "Pitcairn"},
        {label: "Pittston", value: "Pittston"},
        {label: "Plainfield", value: "Plainfield"},
        {label: "Pleasantville", value: "Pleasantville"},
        {label: "Plumville", value: "Plumville"},
        {label: "Plymouth", value: "Plymouth"},
        {label: "Plymouth Meeting", value: "Plymouth Meeting"},
        {label: "Pocono Pines", value: "Pocono Pines"},
        {label: "Point Breeze", value: "Point Breeze"},
        {label: "Point Marion", value: "Point Marion"},
        {label: "Polk", value: "Polk"},
        {label: "Port Allegany", value: "Port Allegany"},
        {label: "Port Clinton", value: "Port Clinton"},
        {label: "Port Matilda", value: "Port Matilda"},
        {label: "Port Royal", value: "Port Royal"},
        {label: "Port Trevorton", value: "Port Trevorton"},
        {label: "Portage", value: "Portage"},
        {label: "Portersville", value: "Portersville"},
        {label: "Portland", value: "Portland"},
        {label: "Potts Grove", value: "Potts Grove"},
        {label: "Pottstown", value: "Pottstown"},
        {label: "Pottsville", value: "Pottsville"},
        {label: "Prompton", value: "Prompton"},
        {label: "Prospect", value: "Prospect"},
        {label: "Prospect Park", value: "Prospect Park"},
        {label: "Punxsutawney", value: "Punxsutawney"},
        {label: "Quakertown", value: "Quakertown"},
        {label: "Quarryville", value: "Quarryville"},
        {label: "Quentin", value: "Quentin"},
        {label: "Railroad", value: "Railroad"},
        {label: "Ramey", value: "Ramey"},
        {label: "Ravine", value: "Ravine"},
        {label: "Reading", value: "Reading"},
        {label: "Reamstown", value: "Reamstown"},
        {label: "Rebersburg", value: "Rebersburg"},
        {label: "Red Hill", value: "Red Hill"},
        {label: "Red Lion", value: "Red Lion"},
        {label: "Reedsville", value: "Reedsville"},
        {label: "Renovo", value: "Renovo"},
        {label: "Republic", value: "Republic"},
        {label: "Reynoldsville", value: "Reynoldsville"},
        {label: "Rheems", value: "Rheems"},
        {label: "Rices Landing", value: "Rices Landing"},
        {label: "Richboro", value: "Richboro"},
        {label: "Richfield", value: "Richfield"},
        {label: "Richland", value: "Richland"},
        {label: "Richlandtown", value: "Richlandtown"},
        {label: "Ridgway", value: "Ridgway"},
        {label: "Ridley Park", value: "Ridley Park"},
        {label: "Riegelsville", value: "Riegelsville"},
        {label: "Rimersburg", value: "Rimersburg"},
        {label: "Ringtown", value: "Ringtown"},
        {label: "Rittenhouse Square", value: "Rittenhouse Square"},
        {label: "Riverside", value: "Riverside"},
        {label: "Roaring Spring", value: "Roaring Spring"},
        {label: "Robesonia", value: "Robesonia"},
        {label: "Robinson", value: "Robinson"},
        {label: "Rochester", value: "Rochester"},
        {label: "Rockhill Furnace", value: "Rockhill Furnace"},
        {label: "Rockwood", value: "Rockwood"},
        {label: "Rome", value: "Rome"},
        {label: "Roscoe", value: "Roscoe"},
        {label: "Rossiter", value: "Rossiter"},
        {label: "Rouseville", value: "Rouseville"},
        {label: "Rouzerville", value: "Rouzerville"},
        {label: "Royersford", value: "Royersford"},
        {label: "Rural Valley", value: "Rural Valley"},
        {label: "Russellton", value: "Russellton"},
        {label: "Saint Clair", value: "Saint Clair"},
        {label: "Saint Marys", value: "Saint Marys"},
        {label: "Saint Michael", value: "Saint Michael"},
        {label: "Saint Petersburg", value: "Saint Petersburg"},
        {label: "Salisbury", value: "Salisbury"},
        {label: "Saltillo", value: "Saltillo"},
        {label: "Saltsburg", value: "Saltsburg"},
        {label: "Sandy Lake", value: "Sandy Lake"},
        {label: "Sandy Ridge", value: "Sandy Ridge"},
        {label: "Saxonburg", value: "Saxonburg"},
        {label: "Sayre", value: "Sayre"},
        {label: "Schaefferstown", value: "Schaefferstown"},
        {label: "Schellsburg", value: "Schellsburg"},
        {label: "Schnecksville", value: "Schnecksville"},
        {label: "Schuylkill Haven", value: "Schuylkill Haven"},
        {label: "Schwenksville", value: "Schwenksville"},
        {label: "Scottdale", value: "Scottdale"},
        {label: "Scranton", value: "Scranton"},
        {label: "Selinsgrove", value: "Selinsgrove"},
        {label: "Sellersville", value: "Sellersville"},
        {label: "Seltzer", value: "Seltzer"},
        {label: "Seneca", value: "Seneca"},
        {label: "Seven Valleys", value: "Seven Valleys"},
        {label: "Seward", value: "Seward"},
        {label: "Sewickley", value: "Sewickley"},
        {label: "Shadyside", value: "Shadyside"},
        {label: "Shamokin", value: "Shamokin"},
        {label: "Shamokin Dam", value: "Shamokin Dam"},
        {label: "Shanksville", value: "Shanksville"},
        {label: "Sharon", value: "Sharon"},
        {label: "Sharon Hill", value: "Sharon Hill"},
        {label: "Sharpsville", value: "Sharpsville"},
        {label: "Sheffield", value: "Sheffield"},
        {label: "Shenandoah", value: "Shenandoah"},
        {label: "Sheppton", value: "Sheppton"},
        {label: "Shickshinny", value: "Shickshinny"},
        {label: "Shippenville", value: "Shippenville"},
        {label: "Shippingport", value: "Shippingport"},
        {label: "Shoemakersville", value: "Shoemakersville"},
        {label: "Silverdale", value: "Silverdale"},
        {label: "Skippack", value: "Skippack"},
        {label: "Slatington", value: "Slatington"},
        {label: "Slickville", value: "Slickville"},
        {label: "Sligo", value: "Sligo"},
        {label: "Slippery Rock", value: "Slippery Rock"},
        {label: "Smethport", value: "Smethport"},
        {label: "Smithfield", value: "Smithfield"},
        {label: "Smithton", value: "Smithton"},
        {label: "Snow Shoe", value: "Snow Shoe"},
        {label: "Snydertown", value: "Snydertown"},
        {label: "Society Hill", value: "Society Hill"},
        {label: "Somerset", value: "Somerset"},
        {label: "Souderton", value: "Souderton"},
        {label: "South Fork", value: "South Fork"},
        {label: "South Heights", value: "South Heights"},
        {label: "South Oakland", value: "South Oakland"},
        {label: "South Park", value: "South Park"},
        {label: "South Philadelphia", value: "South Philadelphia"},
        {label: "South Shore", value: "South Shore"},
        {label: "Southside Flats", value: "Southside Flats"},
        {label: "Southwest", value: "Southwest"},
        {label: "Spartansburg", value: "Spartansburg"},
        {label: "Spring City", value: "Spring City"},
        {label: "Spring Grove", value: "Spring Grove"},
        {label: "Spring House", value: "Spring House"},
        {label: "Spring Mills", value: "Spring Mills"},
        {label: "Spring Mount", value: "Spring Mount"},
        {label: "Springboro", value: "Springboro"},
        {label: "Springdale", value: "Springdale"},
        {label: "Springfield", value: "Springfield"},
        {label: "Squirrel Hill North", value: "Squirrel Hill North"},
        {label: "Squirrel Hill South", value: "Squirrel Hill South"},
        {label: "Starrucca", value: "Starrucca"},
        {label: "State College", value: "State College"},
        {label: "Stewartstown", value: "Stewartstown"},
        {label: "Stockdale", value: "Stockdale"},
        {label: "Stockertown", value: "Stockertown"},
        {label: "Stoneboro", value: "Stoneboro"},
        {label: "Stoystown", value: "Stoystown"},
        {label: "Strasburg", value: "Strasburg"},
        {label: "Strattanville", value: "Strattanville"},
        {label: "Strausstown", value: "Strausstown"},
        {label: "Strip District ", value: "Strip District "},
        {label: "Stroudsburg", value: "Stroudsburg"},
        {label: "Sturgeon", value: "Sturgeon"},
        {label: "Sugar Grove", value: "Sugar Grove"},
        {label: "Summerhill", value: "Summerhill"},
        {label: "Summerville", value: "Summerville"},
        {label: "Summit Hill", value: "Summit Hill"},
        {label: "Summit Station", value: "Summit Station"},
        {label: "Sunbury", value: "Sunbury"},
        {label: "Susquehanna", value: "Susquehanna"},
        {label: "Sutersville", value: "Sutersville"},
        {label: "Swarthmore", value: "Swarthmore"},
        {label: "Sykesville", value: "Sykesville"},
        {label: "Tamaqua", value: "Tamaqua"},
        {label: "Tarentum", value: "Tarentum"},
        {label: "Tatamy", value: "Tatamy"},
        {label: "Taylor", value: "Taylor"},
        {label: "Telford", value: "Telford"},
        {label: "Terre Hill", value: "Terre Hill"},
        {label: "Thompson", value: "Thompson"},
        {label: "Thompsontown", value: "Thompsontown"},
        {label: "Three Springs", value: "Three Springs"},
        {label: "Tidioute", value: "Tidioute"},
        {label: "Tioga", value: "Tioga"},
        {label: "Tionesta", value: "Tionesta"},
        {label: "Tipton", value: "Tipton"},
        {label: "Titusville", value: "Titusville"},
        {label: "Topton", value: "Topton"},
        {label: "Toughkenamon", value: "Toughkenamon"},
        {label: "Towanda", value: "Towanda"},
        {label: "Tower City", value: "Tower City"},
        {label: "Townville", value: "Townville"},
        {label: "Trafford", value: "Trafford"},
        {label: "Tremont", value: "Tremont"},
        {label: "Tresckow", value: "Tresckow"},
        {label: "Trevorton", value: "Trevorton"},
        {label: "Troutville", value: "Troutville"},
        {label: "Troy", value: "Troy"},
        {label: "Trumbauersville", value: "Trumbauersville"},
        {label: "Tunkhannock", value: "Tunkhannock"},
        {label: "Turbotville", value: "Turbotville"},
        {label: "Turtle Creek", value: "Turtle Creek"},
        {label: "Tuscarora", value: "Tuscarora"},
        {label: "Tyrone", value: "Tyrone"},
        {label: "Ulysses", value: "Ulysses"},
        {label: "Union City", value: "Union City"},
        {label: "Union Dale", value: "Union Dale"},
        {label: "Uniontown", value: "Uniontown"},
        {label: "University City", value: "University City"},
        {label: "Ursina", value: "Ursina"},
        {label: "Utica", value: "Utica"},
        {label: "Valencia", value: "Valencia"},
        {label: "Valley View", value: "Valley View"},
        {label: "Vanderbilt", value: "Vanderbilt"},
        {label: "Vandergrift", value: "Vandergrift"},
        {label: "Venango", value: "Venango"},
        {label: "Verona", value: "Verona"},
        {label: "Vintondale", value: "Vintondale"},
        {label: "Wallaceton", value: "Wallaceton"},
        {label: "Walnutport", value: "Walnutport"},
        {label: "Wampum", value: "Wampum"},
        {label: "Warminster", value: "Warminster"},
        {label: "Warren", value: "Warren"},
        {label: "Washington", value: "Washington"},
        {label: "Washingtonville", value: "Washingtonville"},
        {label: "Waterford", value: "Waterford"},
        {label: "Watsontown", value: "Watsontown"},
        {label: "Wattsburg", value: "Wattsburg"},
        {label: "Waymart", value: "Waymart"},
        {label: "Wayne", value: "Wayne"},
        {label: "Waynesboro", value: "Waynesboro"},
        {label: "Waynesburg", value: "Waynesburg"},
        {label: "Weatherly", value: "Weatherly"},
        {label: "Wellsboro", value: "Wellsboro"},
        {label: "Wellsville", value: "Wellsville"},
        {label: "Wernersville", value: "Wernersville"},
        {label: "West Alexander", value: "West Alexander"},
        {label: "West Chester", value: "West Chester"},
        {label: "West Elizabeth", value: "West Elizabeth"},
        {label: "West Grove", value: "West Grove"},
        {label: "West Middlesex", value: "West Middlesex"},
        {label: "West Mifflin", value: "West Mifflin"},
        {label: "West Newton", value: "West Newton"},
        {label: "West Philadelphia", value: "West Philadelphia"},
        {label: "Westfield", value: "Westfield"},
        {label: "Westover", value: "Westover"},
        {label: "Wheatland", value: "Wheatland"},
        {label: "White", value: "White"},
        {label: "White Haven", value: "White Haven"},
        {label: "Whitehall", value: "Whitehall"},
        {label: "Wilkes Barre", value: "Wilkes Barre"},
        {label: "Williamsburg", value: "Williamsburg"},
        {label: "Williamsport", value: "Williamsport"},
        {label: "Williamstown", value: "Williamstown"},
        {label: "Willow Grove", value: "Willow Grove"},
        {label: "Willow Street", value: "Willow Street"},
        {label: "Wilmerding", value: "Wilmerding"},
        {label: "Wilmore", value: "Wilmore"},
        {label: "Wind Gap", value: "Wind Gap"},
        {label: "Windber", value: "Windber"},
        {label: "Windsor", value: "Windsor"},
        {label: "Womelsdorf", value: "Womelsdorf"},
        {label: "Wood", value: "Wood"},
        {label: "Woodbury", value: "Woodbury"},
        {label: "Woodland", value: "Woodland"},
        {label: "Woodlyn", value: "Woodlyn"},
        {label: "Worthington", value: "Worthington"},
        {label: "Wrightsville", value: "Wrightsville"},
        {label: "Wyalusing", value: "Wyalusing"},
        {label: "Wyncote", value: "Wyncote"},
        {label: "Wyoming", value: "Wyoming"},
        {label: "Yeagertown", value: "Yeagertown"},
        {label: "York", value: "York"},
        {label: "York Haven", value: "York Haven"},
        {label: "York Springs", value: "York Springs"},
        {label: "Youngstown", value: "Youngstown"},
        {label: "Youngsville", value: "Youngsville"},
        {label: "Youngwood", value: "Youngwood"},
        {label: "Zelienople", value: "Zelienople"},
        {label: "Zion Grove", value: "Zion Grove"},



    ]

    let searchForm = document.querySelector('form#search');

    if (searchForm) {

        // handles adding icons to locations selected
        var instance = new SelectPure(".locations", {
            options: myOptions,
            multiple: true,
            icon: "fa fa-times",
            inlineIcon: false,
            autocomplete: true,
            onChange: value => { locations = value; }
        });

        let boxy = document.querySelector('.select-pure__select');
        let boxyAutoComplete = document.querySelector('.select-pure__autocomplete');

        boxy.addEventListener("click", (event) => {
            boxyAutoComplete.value = '';
            let boxyOptions = document.querySelectorAll('.select-pure__option');
            boxyOptions.forEach((item)=>{
                item.classList.remove('select-pure__option--hidden');
            });
        });

    };

});